- hosts: localhost

  tasks:
  - name: install git
    yum: name=git state=latest

  - name: download maven
    get_url: url=http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz dest=/var/tmp/apache-maven-3.3.9-bin.tar.gz

  - name: Creates maven directory
    file: path=/usr/local/maven state=directory

  - name: Unarchive the compressed Maven binaries
    unarchive: copy=no src=/var/tmp/apache-maven-3.3.9-bin.tar.gz dest=/usr/local/maven

  - name: Set M2_HOME environment variable
    lineinfile: dest=~/.bash_profile regexp='^M2_HOME.*' line='M2_HOME=/usr/local/maven/apache-maven-3.3.9' insertbefore='^PATH.*'

  - name: Set M2 environment variable
    lineinfile: dest=~/.bash_profile regexp='^M2=.*' line='M2=/usr/local/maven/apache-maven-3.3.9/bin' insertafter='^M2_HOME.*'

  - name: Add Maven binaries to PATH environment variable
    lineinfile: dest=~/.bash_profile state=present backrefs=yes regexp='PATH=(["]*)((?!.*?/usr/local/maven/apache-maven-3.3.9/bin).*?)(["]*)$' line="PATH=\1\2:/usr/local/maven/apache-maven-3.3.9/bin\3"
